files:
  include: "**/*.s+(a|c)ss"
  ignore:
    - node_modules/**/*.*
syntax:
  include:
    - scss
    - sass
resolvers:
  property-sort-order: 1
  attribute-quotes: 1
  no-color-keywords: 1
  no-trailing-zero: 1
  space-after-colon: 1
  space-before-colon: 1
  empty-line-between-blocks: 1
  url-quotes: 1
  zero-unit: 1
  indentation: 0
options:
  optOut: false
